import { Component } from '@angular/core';
import { IProducts } from 'src/app/models/products.model';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.scss']
})
export class productsComponent {
  public productRecords: IProducts[] = [
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 49',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 50',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 51',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 52',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 53',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 49',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 49',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 49',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
    {
      id: 123,
      productImageUrl: '../../../assets/images/Mask Group 32.png',
      productName:
        'Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details Description of product details',
      price: '₪ 49',
      properties: [
        {
          propId: 1,
          propName: 'giga surfing',
          propIcon: '../../../assets/svg/fi-rr-globe.svg',
          propColor: 'blue',
          value: 50,
        },
        {
          propId: 1,
          propName: 'Minutes of conversation',
          propIcon: '../../../assets/svg/fi-rr-dashboard.svg',
          propColor: 'yellow',
          value: 500,
        },
        {
          propId: 1,
          propName: 'SMS',
          propIcon: '../../../assets/svg/fi-rr-comment-alt.svg',
          propColor: 'green',
          value: 300,
        },
        {
          propId: 1,
          propName: 'validity',
          propIcon: '../../../assets/svg/fi-rr-time-check.svg',
          propColor: 'black',
          value: 30,
        },
        {
          propId: 1,
          propName: 'kosher',
          propIcon: '../../../assets/svg/Group 733.svg',
          propColor: 'black',
          value: 300,
        },
        {
          propId: 2,
          propName: "cancelation",
          propIcon: '../../../assets/svg/fi-rr-ban.svg',
          propColor: 'red',
          value: 20,
        },
      ],
    },
  ];
}
